version: '2'
services:
  ryu-mininet:
    build:
      context: .
      args:
        user: iwaseyusuke
    image: iwaseyusuke/ryu-mininet
    tty: true
    privileged: true
    environment:
     - DISPLAY
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
